ejecutar:
	mvn compile assembly:single

javadoc:ejecutar
	mvn javadoc:javadoc
	
normal:javadoc
	java -jar target/Juego_de_la_vida-1.0-SNAPSHOT-jar-with-dependencies.jar 0 10

nave1:javadoc
	java -jar target/Juego_de_la_vida-1.0-SNAPSHOT-jar-with-dependencies.jar 1 10

nave2:javadoc
	java -jar target/Juego_de_la_vida-1.0-SNAPSHOT-jar-with-dependencies.jar 2 10

file:javadoc
	java -jar target/Juego_de_la_vida-1.0-SNAPSHOT-jar-with-dependencies.jar 3 10